spring:
  profiles:
    active: development
  datasource:
    url: jdbc:mysql://vetclinic-db:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: myuser
    password: secret
  application:
    name: consultation-service
  data:
    rest:
      default-page-size: '20'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: alphapawsclinic@gmail.com
    password: jfgz oort ssfv lgtu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: prometheus
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka:password@discovery-server:8761/eureka
#
#app:
#  eureka-server:discovery-server

