spring:
  profiles:
    active: development
  datasource:
    url: ${database.url}
    driverClassName: ${database.driverClassName}
  application:
    name: ${services.consultation.name}
  data:
    rest:
      default-page-size: '20'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
server:
  port: ${services.consultation.port}
