spring:
  profiles:
    active: development
  datasource:
    url: ${database.url}
    driver-class-name: ${database.driver-class-name}
  application:
    name: ${services.doctor.name}
  data:
    rest:
      default-page-size: '20'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: ${database.show-sql}
server:
  port: ${services.doctor.port}
