eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
logging:
  level:
    com:
      netflix:
        discovery: OFF
        eureka: off
server:
  port: 8761

spring:
  profiles:
    active: development
  application:
    name: discovery-server