spring:
  profiles:
    active: development
  datasource:
    url: jdbc:mysql://vetclinic-db:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: myuser
    password: secret
  application:
    name: adoption-service
  data:
    rest:
      default-page-size: '20'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: prometheus


#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka:password@discovery-server:8761/eureka
#
#app:
#  eureka-server:discovery-server

