spring:
  profiles:
    active: development
  datasource:
    url: jdbc:mysql://vetclinic-db:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: myuser
    password: secret
  application:
    name: animal-service
  data:
    rest:
      default-page-size: '20'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
server:
  port: 8081

