server:
  port: 8765

app:
  eureka-server: discovery-server

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

spring:
  profiles:
    active: development
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
#        - id: animal-service
#          uri: http://animal-service:8081/
#          predicates:
#            - Path=/animal-service/**
#        - id: doctor-service
#          uri: http://doctor-service:8084/
#          predicates:
#            - Path=/doctor-service/**
#        - id: consultation-service
#          uri: http://consultation-service:8082/
#          predicates:
#            - Path=/consultation-service/**
#        - id: user-service
#          uri: http://user-service:8085/
#          predicates:
#            - Path=/user-service/**
#        - id: appointment-service
#          uri: http://appointment-service:8083/
#          predicates:
#            - Path=/appointment-service/**
#        - id: adoption-service
#          uri: http://adoption-service:8086/
#          predicates:
#            - Path=/adoption-service/**
        - id: animal-service
          uri: http://localhost:8081/
          predicates:
            - Path=/animal-service/**
        - id: consultation-service
          uri: http://localhost:8082/
          predicates:
            - Path=/consultation-service/**
        - id: appointment-service
          uri: http://localhost:8083/
          predicates:
            - Path=/appointment-service/**
        - id: doctor-service
          uri: http://localhost:8084/
          predicates:
            - Path=/doctor-service/**
        - id: user-service
          uri: http://localhost:8085/
          predicates:
            - Path=/user-service/**
        - id: adoption-service
          uri: http://localhost:8086/
          predicates:
            - Path=/adoption-service/**

          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods: '*'
              allowedHeaders: '*'
      globalcors:
        cors-configurations:
          '[/**]':
            exposed-headers: "*"
            allowedHeaders : "*"
            allowedOrigins: "*"
            allowedMethods: "*"
management:
  endpoints:
    web:
      exposure:
        include: prometheus
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:password@discovery-server:8761/eureka
