server:
  port: ${services.api-gateway.port}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

spring:
  profiles:
    active: development
  application:
    name: ${services.api-gateway.name}
  cloud:
    gateway:
      routes:
        - id: ${services.animal.name}
          uri: ${services.animal.uri}
          predicates:
            - Path=/${services.animal.name}/**
        - id: ${services.consultation.name}
          uri: ${services.consultation.uri}
          predicates:
            - Path=/${services.consultation.name}/**
        - id: ${services.appointment.name}
          uri: ${services.appointment.uri}
          predicates:
            - Path=/${services.appointment.name}/**
        - id: ${services.doctor.name}
          uri: ${services.doctor.uri}
          predicates:
            - Path=/${services.doctor.name}/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods: '*'
              allowedHeaders: '*'
        - id: ${services.user.name}
          uri: ${services.user.uri}
          predicates:
            - Path=/${services.user.name}/**
      globalcors:
        cors-configurations:
          '[/**]':
            exposed-headers: "*"
            allowedHeaders : "*"
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"