server:
  port: 8765

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

spring:
  profiles:
    active: development
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: animal-service
          uri: http://localhost:8081/
          predicates:
            - Path=/animal-service/**
        - id: consultation-service
          uri: http://localhost:8082/
          predicates:
            - Path=/consultation-service/**
        - id: appointment-service
          uri: http://localhost:8083/
          predicates:
            - Path=/appointment-service/**
        - id: doctor-service
          uri: http://localhost:8084/
          predicates:
            - Path=/doctor-service/**
        - id: user-service
          uri: http://localhost:8085/
          predicates:
            - Path=/user-service/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods: '*'
              allowedHeaders: '*'
      globalcors:
        cors-configurations:
          '[/**]':
            exposed-headers: "*"
            allowedHeaders : "*"
            allowedOrigins: http://localhost:4200/front-end
            allowedMethods: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/