#TODO : Add as much environment variables as possible

services:
  doctor:
    port: 8084
    name: doctor-service
  patient:
    port: 8081
    name: patient-service
  appointment:
    port: 8083
    name: appointment-service
