services:
  mysql:
    image: mysql:latest
    container_name: vetclinic-mysql
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=myuser
    ports:
      - 3306:3306
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql