version: '3.8'
services:
  vetclinic-db:
    image: mysql:latest
    container_name: vetclinic-db
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=myuser
    ports:
      - "3306:3306"
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
    networks:
      - vetclinic-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - vetclinic-network

#
#  discovery-server:
#    image: ghergutmadalin/discovery-server:1.1
#    container_name: discovery-server
#    pull_policy: always
#    environment:
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
#    depends_on:
#      - vetclinic-db
#    networks:
#      - vetclinic-network
#
#  api-gateway:
#    image: ghergutmadalin/api-gateway:1.1
#    pull_policy: always
#    container_name: api-gateway
#    ports:
#      - "8765:8765"
#    expose:
#      - "8765"
#    environment:
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
#    depends_on:
#      - discovery-server
#    networks:
#      - vetclinic-network
#
#  animal-service:
#    image: ghergutmadalin/animal-service:1.1
#    pull_policy: always
#    container_name: animal-service
#    environment:
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
#    depends_on:
#      - api-gateway
#      - discovery-server
#    networks:
#      - vetclinic-network
#
#  doctor-service:
#    image: ghergutmadalin/doctor-service:1.1
#    pull_policy: always
#    container_name: doctor-service
#    environment:
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
#    depends_on:
#      - discovery-server
#    networks:
#      - vetclinic-network
#
#  user-service:
#    image: ghergutmadalin/user-service:1.1
#    pull_policy: always
#    container_name: user-service
#    environment:
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
#    depends_on:
#      - discovery-server
#    networks:
#      - vetclinic-network
#
#  consultation-service:
#    image: ghergutmadalin/consultation-service:1.1
#    container_name: consultation-service
#    pull_policy: always
#    environment:
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
#    depends_on:
#      - animal-service
#      - doctor-service
#      - api-gateway
#      - discovery-server
#    networks:
#      - vetclinic-network
#
#  appointment-service:
#    image: ghergutmadalin/appointment-service:1.1
#    container_name: appointment-service
#    pull_policy: always
#    environment:
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
#    depends_on:
#      - doctor-service
#      - api-gateway
#      - discovery-server
#    networks:
#      - vetclinic-network
#
#  adoption-service:
#    image: ghergutmadalin/adoption-service:1.1
#    container_name: adoption-service
#    pull_policy: always
#    environment:
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
#    depends_on:
#      - doctor-service
#      - api-gateway
#      - discovery-server
#    networks:
#      - vetclinic-network
#
#  front-end:
#   image: ghergutmadalin/front-end:1.1
#   container_name: front-end
#   pull_policy: always
#   ports:
#     - "8080:80"
#   depends_on:
#     - api-gateway
#     - discovery-server
#    networks:
#      - vetclinic-network

networks:
  vetclinic-network:
    driver: bridge