spring:
  profiles:
    active: development
  datasource:
    url: jdbc:mysql://3306:3306/$vetclinic-db?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: appointment-service
  data:
    rest:
      default-page-size: '20'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
server:
  port: 8083
